engines:
  # https://docs.codeclimate.com/docs/eslint
  # ES Linting requires an .eslintrc file to tweak checks.
  eslint:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  scss-lint:
    enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      Drupal Commenting FunctionComment TypeHintMissing:
        enabled: false
      Drupal Commenting FunctionComment IncorrectTypeHint:
        enabled: false
      DrupalPractice Commenting CommentEmptyLine SpacingAfter:
        enabled: false
      Drupal NamingConventions ValidFunctionName ScopeNotCamelCaps:
        enabled: false
      Drupal NamingConventions ValidClassName StartWithCaptial:
        enabled: false
      Drupal NamingConventions ValidFunctionName NotCamelCaps:
        enabled: false
      DrupalPractice General ClassName ClassPrefix:
        enabled: false
      Drupal NamingConventions ValidClassName NoUnderscores:
        enabled: false
    config:
      file_extensions: "php,inc,install,module,profile"
      standard: "Drupal,DrupalPractice"
  phpmd:
    enabled: true
    checks:
      Design/WeightedMethodCount:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
    config:
      # https://phpmd.org/rules/index.html
      # The following sets include everything except the controversial set.
      # We can configure these further through .xml files. See docs.
      rulesets: "cleancode,codesize,design,naming,unusedcode"
      # Include special Drupal file extensions.
      file_extensions: "inc,module,profile,php,install"
  # https://docs.codeclimate.com/docs/phan
  phan:
    enabled: true
    config:
      file_extensions: "php,module,profile,inc"
      # minimum-severity: 1
      ignore-undeclared: true
      # quick: true
      # backward-compatiility-checks: true
      # dead-code-detection: true
  # https://docs.codeclimate.com/docs/duplication
  duplication:
    enabled: true
    # exclude_paths:
    #   - examples/
    config:
      languages:
        javascript:
          mass_threshold: 50
          # count_threshold: 3
        php:
          mass_threshold: 60
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
      - todo
      - dpm
      - dsm
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.profile"
  - "**.php"
  - "**.install"
  - "**.css"
  - "**.scss"
  - "**.sass"
  - "**.js"
# exclude these files/paths
exclude_paths:
- "test/**/*"
- "**/vendor/**/*"
- "**.min.*"
- "tests/"
- "spec/"
- "**/vendor/"
